### ISSUE TITLE
Missing annotation file

### ISSUE THREAD

**Issue by Parul-Gupta** [GWwangshuo/VTSCG_LTVRR#1]
Hi authors!

Kudos for this great work, seems quite interesting.
I was trying to run the code when I realised that 1 annotation file is missing:

`Traceback (most recent call last):
  File "main.py", line 299, in <module>
    main(args)
  File "main.py", line 155, in main
    dataset_train = build_dataset(image_set='train', args=args)
  File "/media/1TB/VTSCG_LTVRR/datasets/__init__.py", line 149, in build_dataset
    dataset = DataFactory(
  File "/media/1TB/VTSCG_LTVRR/datasets/__init__.py", line 37, in __init__
    self.dataset = GVQA(
  File "/media/1TB/VTSCG_LTVRR/datasets/gvqa.py", line 125, in __init__
    with open(anno_file, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'data/gvqa/seed0/gvqa_train_annos.json'`

Could you please update the annotations folder with the annotation file.
Thanks a lot!

**Comment by GWwangshuo** [comment]
Hi Parul,

Thanks for your interest in our work. We have updated the description of data annotations. Please check them. 

For the trained models, we will retrain and upload them later since we cannot find the in our training server now.

**Comment by Parul-Gupta** [comment]
Thanks a lot!

**Comment by GWwangshuo** [comment]
> Hi Parul,
> 
> Thanks for your interest in our work. We have updated the description of data annotations. Please check them.
> 
> For the trained models, we will retrain and upload them later since we cannot find the in our training server now.

The trained models have been uploaded to Google Drive. Please find them in the 'Pretrained Weights' of README.
